source 'https://rubygems.org'

gem 'devise'
#gem "bootstrap_form", "~> 4.0"
gem 'bootstrap', '~> 4.4.1'
gem 'font_awesome5_rails'
gem 'webpacker', '~> 4.2', '>= 4.2.2'

# Гем для перевода сообщений девайса
gem 'devise-i18n'
gem 'jquery-rails'
gem 'rails', '~> 6.0.2'

# Гем с русскими форматами (времени и пр.)
gem 'russian'
#gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'byebug'
  gem 'sqlite3', '~> 1.4'
end
